- iam_role:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    name: NewRelicInfrastructure-Integrations
    state: present
    managed_policies:
      - ReadOnlyAccess
    assume_role_policy_document: "{{ lookup('template', 'newrelic-infra-trust-policy.json') }}"

