- name: Copy file to remote
  win_get_url:
    url: "{{ task_item.base_url|default(xvt_public_repo_url) }}/{{ task_item.msi }}"
    dest: '{{ ansible_install_dir|default("c:\ansible_install") }}\{{ task_item.msi }}'

# win_msi does not work for me, run it and the client not installed. The
# msiexec.exe is still running on the remote no error log found yet
# However this works
- name: msi install {{ task_item.msi }}
  win_command: 'msiexec.exe /qn /i c:\ansible_install\{{ task_item.msi }}'
  args:
    creates: '{{ task_item.install_dir }}\{{ task_item.create_file }}'

- block:
    - name: template config for newrelic-infra
      win_template:
        src: "{{ task_item.config_file_name }}.j2"
        dest: '{{ task_item.install_dir }}\{{ task_item.config_file_name }}'
      when: task_item.config_file_name|default()

    - name: start service
      win_service:
        name: "{{ task_item.service_name }}"
        state: started
        start_mode: auto
  when: task_item.service_name|default() == 'newrelic-infra'

- name: template config from field name 'newrelic_config'
  win_copy:
    content: "{{ task_item.config_file_content }}"
    dest: '{{ task_item.install_dir }}\{{ task_item.config_file_name }}'
  when: task_item.config_file_content|default() and task_item.config_file_name|default()
