- name: Copy file to remote
  win_get_url:
    url: "{{ xvt_public_repo_url }}/newrelic-infra.msi"
    dest: '{{ ansible_install_dir|default("c:\ansible_install") }}\newrelic-infra.msi'

- name: msi install newrelic-infra.msi
  win_command: 'msiexec.exe /qn /i c:\ansible_install\newrelic-infra.msi'
  args:
    creates: 'C:\Program Files\New Relic\newrelic-infra\newrelic-infra.exe'

- name: template config
  win_template:
    src: '{{ inventory_dir }}/../files/newrelic-infra.yml'
    dest: 'C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml'

- name: start service
  win_service:
    name: newrelic-infra
    state: started
    start_mode: auto
